@extends('app.mobile.layout')

@section('main-content')
    <div class="mobile-container">

        <!-- Header -->
        <header class="mobile-header">
            <div class="mobile-header-top">
                <div class="mobile-logo">
                    <i class="fas fa-utensils"></i> {{ \Illuminate\Support\Str::upper(\App\Models\Setting::getRestaurantName()) }}
                </div>
                <div style="display:flex; gap:6px; align-items:center;">
                    <button onclick="openFullscreen()" class="js-fullscreen-btn" style="background:#007bff; border:none; color:white; padding:6px 12px; border-radius:4px; font-size:11px; font-weight:700; text-transform:uppercase; cursor:pointer;">
                        <i class="fas fa-expand"></i> SCHERMO
                    </button>
                    <button id="btnLogOperativo" style="background:#dc3545; border:none; color:white; padding:6px 12px; border-radius:4px; font-size:11px; font-weight:700; text-transform:uppercase; cursor:pointer;">
                        <i class="fas fa-chart-line"></i> LOG
                    </button>
                    @if($isAdmin)
                    <button id="btnAddTableMobile" style="background:#dc3545; border:none; color:white; padding:6px 12px; border-radius:4px; font-size:11px; font-weight:700; text-transform:uppercase; cursor:pointer;">
                        <i class="fas fa-plus"></i> TAVOLI
                    </button>
                    @endif
                </div>
            </div>
        </header>

        <!-- Griglia tavoli -->
        <div id="mainViewMobile" class="mobile-page active">
            <div class="mobile-dining-area">
                <div class="mobile-section-title">
                    <i class="fas fa-table me-2"></i> SALA RISTORANTE
                </div>
                <div class="mobile-tables-grid" id="tablesContainerMobile">
                    <!-- Tables generated by JS -->
                </div>
            </div>
        </div>

    </div><!-- /.mobile-container -->

    <!-- ===================================================
         MODIFY ORDER OVERLAY (full-screen, stesso modello desktop)
         =================================================== -->
    <div id="modifyOrderOverlay" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.97); z-index:1000; overflow:hidden;">
        <div style="display:flex; flex-direction:column; height:100%; padding:10px; gap:7px; box-sizing:border-box;">

            <!-- Top bar: tavolo + chiudi -->
            <div style="display:flex; justify-content:space-between; align-items:center; flex-shrink:0; gap:8px;">
                <div style="display:flex; align-items:center; gap:8px; min-width:0;">
                    <span style="font-size:1.3rem; font-weight:700; color:white; line-height:1;" id="modifySelectedTableNumber">-</span>
                    <span style="font-size:0.65rem; color:rgba(255,255,255,0.65); white-space:nowrap;" id="modifyCoversInfo">
                        <i class="fas fa-users" id="modifyCoversIcon"></i>
                        <span id="modifyCoversCount">0</span><span id="modifyCoversLabel"> cop</span>
                    </span>
                </div>
                <button id="closeModifyBtn" style="flex:0 0 auto; background:#dc3545; border:none; color:white; padding:8px 12px; border-radius:5px; font-size:0.7rem; font-weight:700; text-transform:uppercase; letter-spacing:0.4px; cursor:pointer; display:flex; align-items:center; gap:6px;">
                    <i class="fas fa-sign-out-alt"></i> Chiudi e invia
                </button>
            </div>

            <!-- Pannelli ordine + piatti, sempre entrambi visibili -->
            <div style="flex:1; min-height:0; display:flex; flex-direction:column; gap:6px;">

                <!-- ORDINE (55%) -->
                <div id="mobileOverlayOrderTab" style="flex:55 1 0; min-height:0; display:flex; flex-direction:column; overflow:hidden;">
                    <div id="marciaBanner" style="display:none; padding:6px 10px; background:#fed7aa; border:2px solid #9a3412; color:#9a3412; border-radius:6px; font-weight:700; text-align:center; font-size:0.75rem; flex-shrink:0; margin-bottom:4px;">
                        <i class="fas fa-check-circle me-1"></i>
                        <span id="marciaBannerText"></span>
                    </div>
                    <div style="flex:1; min-height:0; overflow-y:auto; -webkit-overflow-scrolling:touch; background:white; border-radius:8px; padding:8px;" id="modifyReceiptItems">
                        <div class="empty-state">
                            <i class="fas fa-shopping-cart"></i>
                            <p>Nessun ordine</p>
                        </div>
                    </div>
                    <!-- Footer sconto/totale (nascosto sul mobile, mantenuto in DOM per JS) -->
                    <div class="overlay-order-footer" style="display:none;">
                        <div class="overlay-discount-row">
                            <span class="discount-label"><i class="fas fa-tag me-1"></i>SCONTO</span>
                            <div class="discount-controls">
                                <button class="discount-type-btn active" id="discountTypePct">%</button>
                                <button class="discount-type-btn" id="discountTypeVal">€</button>
                                <input type="number" id="modifyDiscountInput" min="0" step="0.5" placeholder="0">
                                <button id="btnApplyDiscount" class="discount-apply-btn" onclick="tableOrdersManager.requestDiscountAuth()">
                                    <i class="fas fa-check"></i>
                                </button>
                                <button id="btnResetDiscount" class="discount-reset-btn" style="display:none;" onclick="tableOrdersManager.resetDiscount()">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                        <div class="overlay-total-row">
                            <span id="modifyOriginalAmount" class="original-total"></span>
                            <div class="total-label">TOTALE</div>
                            <div id="modifyTotalAmount" class="total-value">€0.00</div>
                        </div>
                    </div>
                </div>

                <!-- MENU (45%) -->
                <div id="mobileOverlayMenuTab" style="flex:45 1 0; min-height:0; display:flex; flex-direction:column; overflow:hidden;">
                    <div id="modifyMenuContainer" style="flex:1; min-height:0; background:white; border-radius:8px; overflow:hidden;">
                        @livewire('dish-selector-mobile')
                    </div>
                </div>

            </div>

            <!-- Barra azioni: tasti quadrati icona+sigla, sempre visibili -->
            <div class="overlay-actions-bar mobile-actions-bar">
                <button class="action-btn-v" id="btnMarciaTavolo" style="background:#28a745;">
                    <i class="fas fa-play-circle"></i><span>MARCIA</span>
                </button>
                <button class="action-btn-v" id="btnInviaOrdine" style="background:#0d6efd; display:none;">
                    <i class="fas fa-paper-plane"></i><span>INVIA</span>
                </button>
                <button class="action-btn-v" id="btnPreconto" style="background:#17a2b8;">
                    <i class="fas fa-receipt"></i><span>PRE</span>
                </button>
                <button class="action-btn-v" id="btnSpostaTavolo" style="background:#fd7e14;">
                    <i class="fas fa-exchange-alt"></i><span>SPOSTA</span>
                </button>
                <button class="action-btn-v" id="btnRistampaOrdine" style="background:#343a40;">
                    <i class="fas fa-print"></i><span>RIST</span>
                </button>
                <button class="action-btn-v" id="btnModifyComunica" style="background:#6f42c1;">
                    <i class="fas fa-bullhorn"></i><span>COM</span>
                </button>
                <button class="action-btn-v quick-segue-btn" id="btnQuickSegueMobile" type="button"
                        onclick="tableOrdersManager.toggleSegueAfterLast()"
                        aria-pressed="false"
                        style="background:#ffc107; color:#212529;">
                    <i class="fas fa-level-down-alt"></i><span>SEGUE</span>
                </button>
            </div>

        </div>
    </div>

    <!-- Remove Reason Modal -->
    <div id="removeReasonModal" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.7); z-index:3000; align-items:center; justify-content:center;">
        <div style="background:white; border-radius:8px; padding:24px; max-width:380px; width:92%; box-shadow:0 20px 60px rgba(0,0,0,0.5);">
            <h4 style="margin:0 0 18px 0; font-weight:700; text-transform:uppercase; text-align:center; color:#000;">
                <i class="fas fa-trash-alt me-2" style="color:#dc3545;"></i>Motivo della rimozione
            </h4>
            <div style="display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-bottom:14px;">
                <button class="remove-reason-btn" data-reason="Rientro"                  style="padding:11px 6px; background:#f8f9fa; border:2px solid #dee2e6; border-radius:6px; cursor:pointer; font-weight:600; font-size:0.85rem;">Rientro</button>
                <button class="remove-reason-btn" data-reason="Il cliente ha sostituito" style="padding:11px 6px; background:#f8f9fa; border:2px solid #dee2e6; border-radius:6px; cursor:pointer; font-weight:600; font-size:0.85rem;">Ha sostituito</button>
                <button class="remove-reason-btn" data-reason="Errore nel piatto"        style="padding:11px 6px; background:#f8f9fa; border:2px solid #dee2e6; border-radius:6px; cursor:pointer; font-weight:600; font-size:0.85rem;">Errore piatto</button>
                <button class="remove-reason-btn" data-reason="Omaggiato"               style="padding:11px 6px; background:#f8f9fa; border:2px solid #dee2e6; border-radius:6px; cursor:pointer; font-weight:600; font-size:0.85rem;">Omaggiato</button>
                <button class="remove-reason-btn" data-reason="Errore sala"             style="padding:11px 6px; background:#f8f9fa; border:2px solid #dee2e6; border-radius:6px; cursor:pointer; font-weight:600; font-size:0.85rem;">Errore sala</button>
                <button class="remove-reason-btn" data-reason="Errore cucina"           style="padding:11px 6px; background:#f8f9fa; border:2px solid #dee2e6; border-radius:6px; cursor:pointer; font-weight:600; font-size:0.85rem;">Errore cucina</button>
            </div>
            <button id="cancelRemoveReason" style="width:100%; padding:11px; background:#6c757d; border:none; color:white; font-weight:600; text-transform:uppercase; border-radius:6px; cursor:pointer;">ANNULLA</button>
        </div>
    </div>

    <!-- Move Table Modal -->
    <div id="moveTableModal" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.75); z-index:3000; align-items:center; justify-content:center;">
        <div style="background:white; border-radius:8px; padding:22px; max-width:420px; width:92%; box-shadow:0 20px 60px rgba(0,0,0,0.5);">
            <h4 style="margin:0 0 6px 0; font-weight:700; text-transform:uppercase; color:#000;">
                <i class="fas fa-exchange-alt me-2" style="color:#fd7e14;"></i>Sposta Tavolo
            </h4>
            <p style="margin:0 0 16px 0; color:#6c757d; font-size:0.88rem;">
                Tavolo <strong id="moveSourceTableNumber">-</strong> → seleziona destinazione
            </p>
            <div id="moveTableGrid" style="display:grid; grid-template-columns:repeat(5,1fr); gap:7px; max-height:260px; overflow-y:auto; margin-bottom:16px;"></div>
            <button id="cancelMoveTable" style="width:100%; padding:11px; background:#6c757d; border:none; color:white; font-weight:600; text-transform:uppercase; border-radius:6px; cursor:pointer;">ANNULLA</button>
        </div>
    </div>

    <!-- Admin Auth Modal -->
    <div id="adminAuthModal" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.85); z-index:10000; align-items:center; justify-content:center;">
        <div style="background:#1a1a1a; border:2px solid #ffc107; border-radius:8px; padding:28px; max-width:380px; width:92%; box-shadow:0 20px 60px rgba(255,193,7,0.2);">
            <h4 style="margin:0 0 8px 0; font-weight:700; text-transform:uppercase; text-align:center; color:#ffc107;">
                <i class="fas fa-shield-alt me-2"></i>Accesso Amministratore
            </h4>
            <p style="color:#aaa; font-size:0.83rem; margin-bottom:18px; text-align:center;">Inserisci la password admin per accedere al backoffice</p>
            <div style="margin-bottom:10px;">
                <input type="password" id="adminAuthPassword" placeholder="Password admin" inputmode="numeric"
                    style="width:100%; padding:11px 14px; background:#2a2a2a; border:1px solid #555; border-radius:4px; color:#fff; font-size:1rem; box-sizing:border-box;">
            </div>
            <div id="adminAuthError" style="display:none; background:rgba(255,193,7,0.1); border:1px solid #ffc107; border-radius:4px; padding:9px 13px; color:#ffc107; font-size:0.83rem; margin-bottom:12px;">
                <i class="fas fa-exclamation-circle me-2"></i><span id="adminAuthErrorText"></span>
            </div>
            <div style="display:flex; gap:10px;">
                <button id="cancelAdminAuth"  style="flex:1; padding:11px; background:#444; border:none; color:white; font-weight:600; text-transform:uppercase; border-radius:6px; cursor:pointer;">ANNULLA</button>
                <button id="confirmAdminAuth" style="flex:1; padding:11px; background:#ffc107; border:none; color:#000; font-weight:700; text-transform:uppercase; border-radius:6px; cursor:pointer;"><i class="fas fa-sign-in-alt me-1"></i>ACCEDI</button>
            </div>
        </div>
    </div>

    <!-- Modal modifica voce ordine (solo mobile) -->
    <x-mobile-modify-item-modal />

    <!-- Shared modals (stessi del desktop, gestiti da app.js) -->
    <x-product-modal :isMobile="true" />
    <x-operator-auth-modal />
    <x-covers-modal />
    <x-preconto-modal />
    <x-comunica-modal />
    <x-payment-method-modal />
    <x-autoconsumo-modal />
    <x-invoice-modal />
    <x-operational-log-modal />

    {{-- CSS del log operativo su mobile: vedi public/app/css/mobile.css (sezione "LOG OPERATIVO"). --}}

    <!-- Cash Drawer Overlay -->
    <div id="cashDrawerOverlay" style="display:none; position:fixed; inset:0; z-index:9999; background:rgba(0,0,0,0.88); align-items:center; justify-content:center; flex-direction:column;">
        <div style="background:#1a1a2e; border-radius:16px; padding:48px 40px; max-width:420px; width:90%; text-align:center; box-shadow:0 24px 80px rgba(0,0,0,0.6); border:1px solid rgba(255,255,255,0.08);">
            <div style="font-size:3rem; margin-bottom:24px;">💵</div>
            <h2 style="color:#fff; margin:0 0 8px 0; font-size:1.4rem; font-weight:700; letter-spacing:0.5px;">Pagamento in corso</h2>
            <p id="cashDrawerAmount" style="color:#a0aec0; font-size:1.1rem; margin:0 0 32px 0;"></p>

            <div style="display:flex; justify-content:center; margin-bottom:28px;">
                <div style="width:48px; height:48px; border:4px solid rgba(255,255,255,0.15); border-top-color:#4299e1; border-radius:50%; animation:cashDrawerSpin 0.8s linear infinite;"></div>
            </div>

            <p id="cashDrawerStatus" style="color:#cbd5e0; font-size:0.95rem; margin:0 0 32px 0; min-height:1.4em;">In attesa del pagamento dalla cassa automatica...</p>

            <button id="cashDrawerCancelBtn"
                onclick="tableOrdersManager.cancelCashDrawerTransaction()"
                style="background:transparent; border:2px solid #e53e3e; color:#e53e3e; padding:12px 28px; border-radius:8px; font-size:0.95rem; font-weight:600; cursor:pointer; letter-spacing:0.3px; transition:all 0.15s;">
                Annulla transazione
            </button>

            <div id="cashDrawerFallbackSection" style="display:none; margin-top:20px; padding-top:20px; border-top:1px solid rgba(255,255,255,0.1);">
                <p style="color:#f6ad55; font-size:0.9rem; margin:0 0 14px 0; line-height:1.5;">
                    ⚠️ La cassa automatica non risponde.<br>Puoi chiudere il tavolo manualmente.
                </p>
                <button id="cashDrawerFallbackBtn"
                    onclick="tableOrdersManager._executeCashDrawerFallback()"
                    style="background:transparent; border:2px solid #f6ad55; color:#f6ad55; padding:12px 28px; border-radius:8px; font-size:0.95rem; font-weight:600; cursor:pointer; letter-spacing:0.3px; transition:all 0.15s;">
                    Chiudi comunque senza cassa
                </button>
            </div>
        </div>
    </div>
    <style>
        @keyframes cashDrawerSpin { to { transform: rotate(360deg); } }

        /* Tasto veloce Segue nella barra azioni mobile */
        .action-btn-v.quick-segue-btn.active {
            background: #28a745 !important;
            color: #fff !important;
        }
    </style>

    <!-- Revolut Payment Overlay -->
    <div id="revolutPaymentOverlay" style="display:none; position:fixed; inset:0; z-index:9999; background:rgba(0,0,0,0.88); align-items:center; justify-content:center;">
        <div style="background:#0f172a; border-radius:16px; padding:44px 40px; max-width:460px; width:90%; text-align:center; box-shadow:0 24px 80px rgba(0,0,0,0.6); border:1px solid rgba(255,255,255,0.08);">
            <div style="font-size:3rem; margin-bottom:14px;">💳</div>
            <h2 style="color:#fff; margin:0 0 6px 0; font-size:1.4rem; font-weight:700; letter-spacing:0.5px;">In attesa di pagamento</h2>
            <p id="revolutPaymentTerminal" style="color:#94a3b8; font-size:0.85rem; margin:0;"></p>
            <p id="revolutPaymentAmount" style="color:#e2e8f0; font-size:1.6rem; margin:10px 0 24px 0; font-weight:700;"></p>

            <div style="display:flex; justify-content:center; margin-bottom:22px;">
                <div style="width:48px; height:48px; border:4px solid rgba(255,255,255,0.15); border-top-color:#22c55e; border-radius:50%; animation:cashDrawerSpin 0.8s linear infinite;"></div>
            </div>

            <p id="revolutPaymentStatus" style="color:#cbd5e1; font-size:0.95rem; margin:0 0 8px 0; min-height:1.4em;">Avvicinare la carta al terminale Revolut</p>
            <p id="revolutPaymentCountdown" style="color:#64748b; font-size:0.85rem; margin:0 0 24px 0; min-height:1.2em;"></p>

            <div style="display:flex; gap:10px; justify-content:center; flex-wrap:wrap;">
                <button id="revolutPaymentCancelBtn"
                    onclick="tableOrdersManager.cancelRevolutPayment()"
                    style="background:transparent; border:2px solid #ef4444; color:#ef4444; padding:12px 28px; border-radius:8px; font-size:0.95rem; font-weight:600; cursor:pointer; letter-spacing:0.3px; transition:all 0.15s;">
                    Annulla transazione
                </button>
                <button id="revolutPaymentMockBtn"
                    onclick="tableOrdersManager.mockCompleteRevolutPayment()"
                    style="display:none; background:transparent; border:2px solid #22c55e; color:#22c55e; padding:12px 28px; border-radius:8px; font-size:0.95rem; font-weight:600; cursor:pointer; letter-spacing:0.3px; transition:all 0.15s;">
                    Simula pagamento OK
                </button>
            </div>

            <div id="revolutPaymentTimeoutSection" style="display:none; margin-top:20px; padding-top:20px; border-top:1px solid rgba(255,255,255,0.1);">
                <p style="color:#fbbf24; font-size:0.9rem; margin:0; line-height:1.5;">
                    ⚠️ Il pagamento sta impiegando più del previsto.<br>Verifica sul terminale o annulla per riprovare.
                </p>
            </div>
        </div>
    </div>

    <!-- Cash Drawer Fallback Alert (rimane visibile fino alla conferma dell'operatore) -->
    <div id="cashDrawerFallbackAlert" style="display:none; position:fixed; inset:0; z-index:10000; background:rgba(0,0,0,0.92); align-items:center; justify-content:center;">
        <div style="background:#2d1a00; border:2px solid #f6ad55; border-radius:16px; padding:40px 36px; max-width:440px; width:90%; text-align:center; box-shadow:0 24px 80px rgba(0,0,0,0.7);">
            <div style="font-size:3rem; margin-bottom:20px;">⚠️</div>
            <h2 style="color:#f6ad55; margin:0 0 16px 0; font-size:1.3rem; font-weight:700; letter-spacing:0.3px;">Cassa automatica non raggiungibile</h2>
            <p style="color:#fbd38d; font-size:1rem; margin:0 0 12px 0; line-height:1.6;">
                Il tavolo è stato chiuso e il pagamento è stato registrato come <strong>contanti</strong>.
            </p>
            <p style="color:#fbd38d; font-size:1rem; margin:0 0 32px 0; line-height:1.6;">
                La cassa automatica non ha confermato l'operazione.<br>
                <strong>Verifica manualmente l'incasso.</strong>
            </p>
            <button
                onclick="document.getElementById('cashDrawerFallbackAlert').style.display='none'"
                style="background:#f6ad55; border:none; color:#1a1a00; padding:14px 40px; border-radius:8px; font-size:1rem; font-weight:700; cursor:pointer; letter-spacing:0.3px;">
                Ho verificato, chiudi
            </button>
        </div>
    </div>

    <!-- Notification -->
    <div id="notification" class="notification">
        <span id="notificationText">Operazione completata!</span>
        <span id="notificationClose" style="display:none; margin-left:auto; font-weight:700; cursor:pointer; opacity:0.6;" onclick="document.getElementById('notification').style.display='none'">✕</span>
    </div>

@endsection
